// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwdBpaJ4dJ_-y1BWonETKKt-3yQBqVpg',
    appId: '1:773699926212:web:137779f8523a2abb4e7191',
    messagingSenderId: '773699926212',
    projectId: 'test-firebase-with-flutt-30ba6',
    authDomain: 'test-firebase-with-flutt-30ba6.firebaseapp.com',
    storageBucket: 'test-firebase-with-flutt-30ba6.firebasestorage.app',
    measurementId: 'G-2R4WMSRRDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWTsg8qYGz-5BEg7a2lnSXlzZ3eqdK46o',
    appId: '1:773699926212:android:0a90bf2039fba75d4e7191',
    messagingSenderId: '773699926212',
    projectId: 'test-firebase-with-flutt-30ba6',
    storageBucket: 'test-firebase-with-flutt-30ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6t7dXjbVEgZ_FCPrM-3VIcWL7qAMxxyg',
    appId: '1:773699926212:ios:bcbaa6d868fe8f2f4e7191',
    messagingSenderId: '773699926212',
    projectId: 'test-firebase-with-flutt-30ba6',
    storageBucket: 'test-firebase-with-flutt-30ba6.firebasestorage.app',
    iosBundleId: 'com.erojjla.pvMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6t7dXjbVEgZ_FCPrM-3VIcWL7qAMxxyg',
    appId: '1:773699926212:ios:bcbaa6d868fe8f2f4e7191',
    messagingSenderId: '773699926212',
    projectId: 'test-firebase-with-flutt-30ba6',
    storageBucket: 'test-firebase-with-flutt-30ba6.firebasestorage.app',
    iosBundleId: 'com.erojjla.pvMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiwdBpaJ4dJ_-y1BWonETKKt-3yQBqVpg',
    appId: '1:773699926212:web:1ef959ae878b71084e7191',
    messagingSenderId: '773699926212',
    projectId: 'test-firebase-with-flutt-30ba6',
    authDomain: 'test-firebase-with-flutt-30ba6.firebaseapp.com',
    storageBucket: 'test-firebase-with-flutt-30ba6.firebasestorage.app',
    measurementId: 'G-5ZCB1GPL2J',
  );
}
